from PySide import QtCore, QtGui
import maya.OpenMayaUI as omu
import shiboken

def maya_main_window():
    ptr = omu.MQtUtil.mainWindow()
    return shiboken.wrapInstance(long(ptr), QtGui.QDialog)
        
class Ui_commandButtonDialog(object):
    def setupUi(self, commandButtonDialog):
        commandButtonDialog.setObjectName("commandButtonDialog")
        commandButtonDialog.resize(495, 417)
        self.verticalLayout_2 = QtGui.QVBoxLayout(commandButtonDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.codeEdit = QtGui.QPlainTextEdit(commandButtonDialog)
        self.codeEdit.setFrameShadow(QtGui.QFrame.Sunken)
        self.codeEdit.setObjectName("codeEdit")
        self.verticalLayout_2.addWidget(self.codeEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(commandButtonDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelEdit = QtGui.QLineEdit(commandButtonDialog)
        self.labelEdit.setObjectName("labelEdit")
        self.horizontalLayout.addWidget(self.labelEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(commandButtonDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.tooltipEdit = QtGui.QLineEdit(commandButtonDialog)
        self.tooltipEdit.setObjectName("tooltipEdit")
        self.horizontalLayout_2.addWidget(self.tooltipEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(commandButtonDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.tagsEdit = QtGui.QLineEdit(commandButtonDialog)
        self.tagsEdit.setObjectName("tagsEdit")
        self.horizontalLayout_4.addWidget(self.tagsEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(commandButtonDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.widthSpin = QtGui.QSpinBox(commandButtonDialog)
        self.widthSpin.setMaximum(1000)
        self.widthSpin.setObjectName("widthSpin")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.widthSpin)
        self.label_3 = QtGui.QLabel(commandButtonDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.heightSpin = QtGui.QSpinBox(commandButtonDialog)
        self.heightSpin.setObjectName("heightSpin")
        self.heightSpin.setMaximum(1000)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.heightSpin)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.saveButton = QtGui.QPushButton(commandButtonDialog)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.closeButton = QtGui.QPushButton(commandButtonDialog)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(commandButtonDialog)
        QtCore.QMetaObject.connectSlotsByName(commandButtonDialog)

    def retranslateUi(self, commandButtonDialog):
        commandButtonDialog.setWindowTitle(QtGui.QApplication.translate("commandButtonDialog", "Command Button", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("commandButtonDialog", "Label:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("commandButtonDialog", "Tooltip:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("commandButtonDialog", "Tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.tagsEdit.setPlaceholderText(QtGui.QApplication.translate("commandButtonDialog", "space separated", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("commandButtonDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("commandButtonDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("commandButtonDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("commandButtonDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))



class Ui_selectorDialog(object):
    def setupUi(self, selectorDialog):
        selectorDialog.setObjectName("selectorDialog")
        selectorDialog.resize(360, 241)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(selectorDialog.sizePolicy().hasHeightForWidth())
        selectorDialog.setSizePolicy(sizePolicy)
        self.colorCheckbox = QtGui.QCheckBox(selectorDialog)
        self.colorCheckbox.setGeometry(QtCore.QRect(180, 140, 171, 17))
        self.colorCheckbox.setObjectName("colorCheckbox")
        self.horizontalLayoutWidget = QtGui.QWidget(selectorDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(179, 80, 171, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.colorEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.colorEdit.setObjectName("colorEdit")
        self.horizontalLayout.addWidget(self.colorEdit)
        self.verticalLayoutWidget = QtGui.QWidget(selectorDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.targetList = QtGui.QListWidget(self.verticalLayoutWidget)
        self.targetList.setObjectName("targetList")
        self.verticalLayout_2.addWidget(self.targetList)
        self.loadButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout_2.addWidget(self.loadButton)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(selectorDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(180, 50, 171, 22))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tooltipEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.tooltipEdit.setObjectName("tooltipEdit")
        self.horizontalLayout_2.addWidget(self.tooltipEdit)
        self.saveButton = QtGui.QPushButton(selectorDialog)
        self.saveButton.setGeometry(QtCore.QRect(250, 180, 101, 23))
        self.saveButton.setObjectName("saveButton")
        self.closeButton = QtGui.QPushButton(selectorDialog)
        self.closeButton.setGeometry(QtCore.QRect(250, 210, 101, 23))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayoutWidget_3 = QtGui.QWidget(selectorDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(179, 20, 171, 22))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tagsEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.tagsEdit.setObjectName("tagsEdit")
        self.horizontalLayout_3.addWidget(self.tagsEdit)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(selectorDialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(180, 110, 171, 22))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.radiusSpin = QtGui.QSpinBox(self.horizontalLayoutWidget_4)
        self.radiusSpin.setMaximum(1000)
        self.radiusSpin.setProperty("value", 0)
        self.radiusSpin.setObjectName("radiusSpin")
        self.horizontalLayout_4.addWidget(self.radiusSpin)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)

        self.retranslateUi(selectorDialog)
        QtCore.QMetaObject.connectSlotsByName(selectorDialog)

    def retranslateUi(self, selectorDialog):
        selectorDialog.setWindowTitle(QtGui.QApplication.translate("selectorDialog", "Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.colorCheckbox.setText(QtGui.QApplication.translate("selectorDialog", "Use 1st object\'s override color", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("selectorDialog", "Color:   ", None, QtGui.QApplication.UnicodeUTF8))
        self.colorEdit.setText(QtGui.QApplication.translate("selectorDialog", "#FFFFFF", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("selectorDialog", "Load selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("selectorDialog", "Tooltip: ", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("selectorDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("selectorDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("selectorDialog", "Tags:    ", None, QtGui.QApplication.UnicodeUTF8))
        self.tagsEdit.setPlaceholderText(QtGui.QApplication.translate("selectorDialog", "space separated", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("selectorDialog", "Radius:", None, QtGui.QApplication.UnicodeUTF8))


class Ui_sliderDialog(object):
    def setupUi(self, sliderDialog):
        sliderDialog.setObjectName("sliderDialog")
        sliderDialog.resize(336, 291)
        self.verticalLayout_2 = QtGui.QVBoxLayout(sliderDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(sliderDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.attributeEdit = QtGui.QLineEdit(sliderDialog)
        self.attributeEdit.setObjectName("attributeEdit")
        self.horizontalLayout.addWidget(self.attributeEdit)
        self.loadButton = QtGui.QPushButton(sliderDialog)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(sliderDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.minValueSpin = QtGui.QDoubleSpinBox(sliderDialog)
        self.minValueSpin.setMinimum(-10000)
        self.minValueSpin.setMaximum(10000)
        self.minValueSpin.setMaximumSize(QtCore.QSize(60, 16777215))
        self.minValueSpin.setObjectName("minValueSpin")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.minValueSpin)
        self.label_3 = QtGui.QLabel(sliderDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.maxValueSpin = QtGui.QDoubleSpinBox(sliderDialog)
        self.maxValueSpin.setMinimum(-10000)
        self.maxValueSpin.setMaximum(10000)
        self.maxValueSpin.setMaximumSize(QtCore.QSize(60, 16777215))
        self.maxValueSpin.setObjectName("maxValueSpin")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.maxValueSpin)
        self.label_4 = QtGui.QLabel(sliderDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.defaultValueSpin = QtGui.QSpinBox(sliderDialog)
        self.defaultValueSpin.setMaximum(100)
        self.defaultValueSpin.setMaximumSize(QtCore.QSize(60, 16777215))
        self.defaultValueSpin.setObjectName("defaultValueSpin")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.defaultValueSpin)
        self.clampToIntCheckbox = QtGui.QCheckBox(sliderDialog)
        self.clampToIntCheckbox.setObjectName("clampToIntCheckbox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.clampToIntCheckbox)
        self.label_5 = QtGui.QLabel(sliderDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.tooltipEdit = QtGui.QLineEdit(sliderDialog)
        self.tooltipEdit.setObjectName("tooltipEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.tooltipEdit)
        self.label_6 = QtGui.QLabel(sliderDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.tagsEdit = QtGui.QLineEdit(sliderDialog)
        self.tagsEdit.setObjectName("tagsEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.tagsEdit)
        self.label_8 = QtGui.QLabel(sliderDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lengthSpin = QtGui.QSpinBox(sliderDialog)
        self.lengthSpin.setMaximum(1000)
        self.lengthSpin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lengthSpin.setObjectName("lengthSpin")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lengthSpin)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.saveButton = QtGui.QPushButton(sliderDialog)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.closeButton = QtGui.QPushButton(sliderDialog)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(sliderDialog)
        QtCore.QMetaObject.connectSlotsByName(sliderDialog)

    def retranslateUi(self, sliderDialog):
        sliderDialog.setWindowTitle(QtGui.QApplication.translate("sliderDialog", "Slider", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("sliderDialog", "Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("sliderDialog", "Load object", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("sliderDialog", "Minimum attribute value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("sliderDialog", "Maximum attribute value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("sliderDialog", "Default slider value:", None, QtGui.QApplication.UnicodeUTF8))
        self.clampToIntCheckbox.setText(QtGui.QApplication.translate("sliderDialog", "Clamp to closest integer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("sliderDialog", "Tooltip:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("sliderDialog", "Tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.tagsEdit.setPlaceholderText(QtGui.QApplication.translate("sliderDialog", "space separated", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("sliderDialog", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("sliderDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("sliderDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))



class Ui_checkboxDialog(object):
    def setupUi(self, checkboxDialog):
        checkboxDialog.setObjectName("checkboxDialog")
        checkboxDialog.resize(461, 363)
        self.verticalLayout = QtGui.QVBoxLayout(checkboxDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultStateCheckbox = QtGui.QCheckBox(checkboxDialog)
        self.defaultStateCheckbox.setObjectName("defaultStateCheckbox")
        self.verticalLayout.addWidget(self.defaultStateCheckbox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(checkboxDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.labelEdit = QtGui.QLineEdit(checkboxDialog)
        self.labelEdit.setObjectName("labelEdit")
        self.horizontalLayout_3.addWidget(self.labelEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(checkboxDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tagsEdit = QtGui.QLineEdit(checkboxDialog)
        self.tagsEdit.setObjectName("tagsEdit")
        self.horizontalLayout_2.addWidget(self.tagsEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.directControlRadio = QtGui.QRadioButton(checkboxDialog)
        self.directControlRadio.setChecked(True)
        self.directControlRadio.setObjectName("directControlRadio")
        self.verticalLayout.addWidget(self.directControlRadio)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(checkboxDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.attributeEdit = QtGui.QLineEdit(checkboxDialog)
        self.attributeEdit.setObjectName("attributeEdit")
        self.horizontalLayout.addWidget(self.attributeEdit)
        self.loadButton = QtGui.QPushButton(checkboxDialog)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scriptRadio = QtGui.QRadioButton(checkboxDialog)
        self.scriptRadio.setObjectName("scriptRadio")
        self.verticalLayout.addWidget(self.scriptRadio)
        self.codeEdit = QtGui.QPlainTextEdit(checkboxDialog)
        self.codeEdit.setObjectName("codeEdit")
        self.verticalLayout.addWidget(self.codeEdit)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.saveButton = QtGui.QPushButton(checkboxDialog)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_4.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.closeButton = QtGui.QPushButton(checkboxDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_5.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(checkboxDialog)
        QtCore.QMetaObject.connectSlotsByName(checkboxDialog)

    def retranslateUi(self, checkboxDialog):
        checkboxDialog.setWindowTitle(QtGui.QApplication.translate("checkboxDialog", "Checkbox", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultStateCheckbox.setText(QtGui.QApplication.translate("checkboxDialog", "Default state", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("checkboxDialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("checkboxDialog", "Tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.tagsEdit.setPlaceholderText(QtGui.QApplication.translate("checkboxDialog", "space separated", None, QtGui.QApplication.UnicodeUTF8))
        self.directControlRadio.setText(QtGui.QApplication.translate("checkboxDialog", "Control attribute directly", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("checkboxDialog", "Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("checkboxDialog", "Load object", None, QtGui.QApplication.UnicodeUTF8))
        self.scriptRadio.setText(QtGui.QApplication.translate("checkboxDialog", "Execute script on state change", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("checkboxDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("checkboxDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

